### ISSUE TITLE
Advanced Button Block - not correctly sized

### ISSUE THREAD

**Issue by dch-control** [pogla/gutenberg-advanced-button#2]
Hi, 

I'm trying out some of the Kadence Blocks and I'm struggling with the Advanced Button block.  In edit mode it all seems wonderful, allowing me to change all the properties of the button that I want.  But once published, irrespective of the size I made the button (even if HUGE), it only displays as a button so tiny that it is impossible to read the text, and the border consumes about half the image.  The button does perform the expected functions, it's just that it is totally unusable!

I'm using WordPress v5.1.1 with theme Twenty-Seventeen and Options for Twenty-Seventeen v1.9.0 by webd.uk.  Am I missing something obvious, or is there a problem that hasn't been reported yet?

**Comment by dch-control** [comment]
Update 09 May 2019:  Installed latest udates (available in last few days) to Wordpress v5.2, theme Twenty-Seventeen v2.2, Options for Twenty-Seventeen v1.9.5 and Kadence Blocks v1.5.3.  Delighted to tell you that the reported issue has been resolved.

**Comment by pogla** [comment]
@dch-control Thanks for reporting the issue and I am sorry I couldn't attend to it before. I created a fix and it should now be compatible with the latest WordPress 5.2.2.

**Comment by dch-control** [comment]
Thank you very much for your message.
 
I’m afraid I have noticed the Kadence Row Layout block misbehaving in Twenty-Seventeen theme.  Can I report that issue somehow please?
 
Kind regards,
David Hobbs (dch-control).
